{% set version = "1.4.5" %}

package:
  name: jake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jake/jake-{{ version }}.tar.gz
  sha256: 856b167ea30606625fcb857c2c32d4568f2c72bf84dee8d8923d964b01cf4c8f

build:
  number: 0
  noarch: python
  entry_points:
    - jake = jake.app:main
  script:
    - {{ PYTHON }} -m pip install . -vv
    - |-
      {{ PYTHON }} -c "(__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').unlink()"


requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - python >=3.6
    # these get translated from ~^ to concrete values in poetry-generated setup.py
    - cyclonedx-bom >=2.0.1,<3.0.0
    - ossindex-lib >=0.2.1
    - polling2 >=0.5.0
    - pyfiglet >=0.8.post1
    - request
    - rich >=10.15.2

test:
  imports:
    - jake
    - jake.app
  commands:
    - pip check
    - jake --version
    - jake --help
    # TODO: see https://github.com/sonatype-nexus-community/jake/issues/66
    - conda list --explicit | jake sbom -t CONDA
  requires:
    - pip

about:
  home: https://github.com/sonatype-nexus-community/jake
  summary: An OSS Index integration to check for vulnerabilities in your Conda environments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
